[parity]
chain = "demo-spec.json"
base_path = "parity3"
[network]
port = 30303
reserved_peers = "bootnodes.txt"
[rpc]
port = 8543
apis = ["all"]
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8453
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xdbfea9bdd79242a872a33926797bf64d7614fc87"
gas_floor_target = "16000000"
reseal_on_txs = "none"
