[parity]
chain = "demo-spec.json"
base_path = "parity0"
[network]
port = 30300
reserved_peers = "bootnodes.txt"
[rpc]
port = 8540
apis = ["all"]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8450
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xed68e06d0f9012c6b7ae9414d8bfb641a0d00704"
reseal_on_txs = "none"
force_sealing = true
