[parity]
chain = "demo-spec.json"
base_path = "parity2"
[network]
port = 30302
reserved_peers = "bootnodes.txt"
[rpc]
port = 8542
apis = ["all"]
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8452
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xcfbfe6b2bfbb31ab2e0b8d5a6886d84d250e0ec8"
gas_floor_target = "16000000"
reseal_on_txs = "none"
