[parity]
chain = "demo-spec2.json"
base_path = "parity2"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
hosts = ["all"]
[ui]
port = 8182
[websockets]
port = 8452
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
gas_floor_target = "16000000"
reseal_on_txs = "none"
