[parity]
chain = "demo-spec.json"
base_path = "parity4"
[network]
port = 30304
reserved_peers = "bootnodes.txt"
[rpc]
port = 8544
apis = ["all"]
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8454
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x7d02c71745aeaa08499d935f76215a862c9cd202"
gas_floor_target = "16000000"
reseal_on_txs = "none"
